if [ -f /tmp/.echo ]; then
  echo "Using: $(pwd)/.zlogout"
fi
#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Print the message.

printf "\n$(fg_yellow "Thank you. Come again!")\n"

exit
