# ~/.bash_profile: executed by the command interpreter for login shells.
# This file is not read by bash(1) if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile
#umask 022
if [ -f "/tmp/.echo" ]; then
	echo "Using: ~/.bash_profile"
fi

OS=`uname`

# if running bash
if [ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ]; then
		. $HOME/.bashrc
fi

# set PATH so it includes user's private bin if it exists
#if [ -d "$HOME/bin" ] ; then
#	PATH="$HOME/bin:$PATH"
#fi

# set color
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export BASH_SILENCE_DEPRECATION_WARNING=1
