#!/bin/bash
# OS Specific PATH is in the OS files below
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

if [ ! -d "$HOME/bin" ] ; then
	mkdir ${HOME}/bin
fi
export PATH="${HOME}/bin:$PATH"
if [ "$(uname)" = "Darwin" ]; then
	export PATH="/sbin:$PATH"
	export PATH=${PATH}:~/Library/Python/2.7/bin
	#export PATH=${PATH}:/Applications/lb5pa1
	export PATH=${PATH}:/Applications/lb5pa2
else
	export PATH="/usr/local/bin:${PATH}"
fi
# set PATH so it includes user's private bin if it exists
export PGPPATH=~/.pgp
if [[ ! $PATH =~ .*:/usr/local/mailman/bin:.* ]]; then
	export PATH="${PATH}:/usr/local/mailman/bin"
fi
export PATH="${PATH}:/usr/local/sbin"
export PATH="${PATH}:/usr/sbin"
export PATH="${PATH}:/usr/bin"
export PATH="${PATH}:/bin"
#export PATH="${PATH}:/usr/local/opt/findutils/libexec/gnubin"
