" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')
" Declare the list of plugins.
Plug 'airblade/vim-gitgutter'
Plug 'andymass/vim-matchup'
Plug 'bling/vim-bufferline'
Plug 'codota/TabNine'
Plug 'editorconfig/editorconfig-vim'
Plug 'edkolev/tmuxline.vim'
Plug 'farmergreg/vim-lastplace'
Plug 'frazrepo/vim-rainbow'
Plug 'itchyny/lightline.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/seoul256.vim'
Plug 'mattn/emmet-vim'
Plug 'mileszs/ack.vim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'powerline/fonts'
Plug 'preservim/nerdtree'
Plug 'rafi/awesome-vim-colorschemes'
Plug 'sheerun/vim-polyglot'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-scripts/bash-support.vim'
Plug 'vim-syntastic/syntastic'
Plug 'w0rp/ale'
" The following handles context colors
Plug 'godlygeek/csapprox'
"" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Mouse
set mouse=a

" Settings for vim-indent-guides
colorscheme darkblack
"colorscheme candycode
"colorscheme molokai
let g:airline_powerline_fonts = 1
let g:loaded_clipboard_provider = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_color_change_percent = 3
let g:indent_guides_enable_on_vim_startup = 1

" Airline adjustments
"   Set Airline Theme
"let g:airline_theme='alduin'
"let g:airline_theme='angr'
"let g:airline_theme='atomic'
"let g:airline_theme='aurora'
"let g:airline_theme='ayu_mirage'
"let g:airline_theme='badcat'
"let g:airline_theme='badwolf'
"let g:airline_theme='base16'
"let g:airline_theme='base16_3024'
"let g:airline_theme='base16_apathy'
"let g:airline_theme='base16_ashes'
"let g:airline_theme='base16_atelierdune'
"let g:airline_theme='base16_atelierforest'
"let g:airline_theme='base16_atelierheath'
"let g:airline_theme='base16_atelierlakeside'
"let g:airline_theme='base16_atelierseaside'
"let g:airline_theme='base16_bespin'
"let g:airline_theme='base16_brewer'
"let g:airline_theme='base16_bright'
"let g:airline_theme='base16_chalk'
"let g:airline_theme='base16_classic'
"let g:airline_theme='base16_codeschool'
"let g:airline_theme='base16_colors'
"let g:airline_theme='base16_default'
"let g:airline_theme='base16_eighties'
"let g:airline_theme='base16_embers'
"let g:airline_theme='base16_flat'
"let g:airline_theme='base16_google'
"let g:airline_theme='base16_grayscale'
"let g:airline_theme='base16_greenscreen'
"let g:airline_theme='base16_harmonic16'
"let g:airline_theme='base16_hopscotch'
"let g:airline_theme='base16_isotope'
"let g:airline_theme='base16_londontube'
"let g:airline_theme='base16_marrakesh'
"let g:airline_theme='base16_mocha'
"let g:airline_theme='base16_monokai'
"let g:airline_theme='base16_nord'
"let g:airline_theme='base16_ocean'
"let g:airline_theme='base16_oceanicnext'
"let g:airline_theme='base16_paraiso'
"let g:airline_theme='base16_pop'
"let g:airline_theme='base16_railscasts'
"let g:airline_theme='base16_seti'
"let g:airline_theme='base16_shapeshifter'
"let g:airline_theme='base16_shell'
"let g:airline_theme='base16_solarized'
"let g:airline_theme='base16_spacemacs'
"let g:airline_theme='base16_summerfruit'
"let g:airline_theme='base16_tomorrow'
"let g:airline_theme='base16_twilight'
"let g:airline_theme='base16color'
"let g:airline_theme='behelit'
"let g:airline_theme='biogoo'
"let g:airline_theme='bubblegum'
"let g:airline_theme='cobalt2'
"let g:airline_theme='cool'
"let g:airline_theme='dark_minimal'
"let g:airline_theme='deus'
"let g:airline_theme='distinguished'
"let g:airline_theme='dracula'
"let g:airline_theme='durant'
"let g:airline_theme='fairyfloss'
"let g:airline_theme='hybrid'
"let g:airline_theme='hybridline'
"let g:airline_theme='jellybeans'
"let g:airline_theme='jet'
"let g:airline_theme='kalisi'
"let g:airline_theme='kolor'
"let g:airline_theme='laederon'
"let g:airline_theme='light'
"let g:airline_theme='lucius'
"let g:airline_theme='luna'
"let g:airline_theme='minimalist'
"let g:airline_theme='molokai'
"let g:airline_theme='monochrome'
"let g:airline_theme='murmur'
"let g:airline_theme='night_owl'
"let g:airline_theme='onedark'
"let g:airline_theme='papercolor'
"let g:airline_theme='peaksea'
"let g:airline_theme='powerlineish'
"let g:airline_theme='qwq'
"let g:airline_theme='raven'
"let g:airline_theme='ravenpower'
"let g:airline_theme='seagull'
"let g:airline_theme='serene'
"let g:airline_theme='sierra'
"let g:airline_theme='silver'
"let g:airline_theme='simple'
"let g:airline_theme='soda'
"let g:airline_theme='sol'
"let g:airline_theme='solarized'
"let g:airline_theme='solarized_flood'
"let g:airline_theme='term'
"let g:airline_theme='term_light'
"let g:airline_theme='tomorrow'
"let g:airline_theme='ubaryd'
"let g:airline_theme='understated'
"let g:airline_theme='vice'
"let g:airline_theme='violet'
"let g:airline_theme='wombat'
"let g:airline_theme='xtermlight'
"let g:airline_theme='zenburn'

set encoding=utf-8
"set background=dark
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
set guifont=Source\ Code\ Pro\ for\ Powerline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
"let g:airline_right_sep='<'
"let g:airline_right_sep='<'
let g:airline_detect_modified=1
" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '☰'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.maxlinenr = '㏑'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = 'Ɇ'
let g:airline_symbols.whitespace = 'Ξ'

if (&ft=='sh'||&ft=='bash'||&ft=='zsh')
  let b:is_bash = 1
  set syntax=bash
  set ft=bash
endif
" NerdTreeTogg
map <C-o> :NERDTreeToggle<CR>
" Indentation & Tabs
set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
" set expandtab
set smarttab
" Display & format
set number
set textwidth=0
set wrapmargin=0
set wrap
set linebreak
set columns=80
set showmatch
" Search
set hlsearch
set incsearch
set ignorecase
set smartcase
" Browse & Scroll
set scrolloff=5
" Status Line
" Option 2
" Some funky status bar code its seems
" https://stackoverflow.com/questions/9065941/how-can-i-change-vim-status-line-colour
set laststatus=2            " set the bottom status bar
" Make double-<Esc> clear search highlights
nnoremap <silent> <Esc><Esc> <Esc>:nohlsearch<CR><Esc>
function! ModifiedColor()
    if &mod == 1
        hi statusline guibg=White ctermfg=8 guifg=OrangeRed4 ctermbg=15
    else
        hi statusline guibg=White ctermfg=8 guifg=DarkSlateGray ctermbg=15
    endif
endfunction
au InsertLeave,InsertEnter,BufWritePost   * call ModifiedColor()
" default the statusline when entering Vim
hi statusline guibg=White ctermfg=8 guifg=DarkSlateGray ctermbg=15
" Formats the statusline
set statusline=%f                           " file name
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%y      "filetype
set statusline+=%h      "help file flag
set statusline+=[%{getbufvar(bufnr('%'),'&mod')?'modified':'saved'}]      
"modified flag
set statusline+=%r      "read only flag
set statusline+=\ %=                   " align left
set statusline+=Line:%l/%L[%p%%]       " line X of Y [percent of file]
set statusline+=\ Col:%c               " current column
set statusline+=\ Buf:%n               " Buffer number
set statusline+=\ [%b][0x%B]\          " ASCII and byte code under cursor
" Spell
set spell spelllang=en_us
" Miscellaneous
set nobackup
set noswapfile
set autochdir
set undofile
set visualbell
set errorbells
" Fix Paste/noPaste mode to be automatic
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
