#!/bin/bash
# OS Specific PATH is in the OS files below
path_remove () {
	if [ -z ${1} ]; then
		echo "Usage: ${funcstack[1]} PATH_To_Remove"
	else
  # Delete path by parts so we can never accidentally remove sub paths
		PATH=${PATH//":$1:"/":"} # delete any instances in the middle
		PATH=${PATH/#"$1:"/} # delete any instance at the beginning
		PATH=${PATH/%":$1"/} # delete any instance in the at the end
	fi
}

export PATH="/usr/local/opt/gnu-getopt/bin:${PATH}"

if [ ! -d "$HOME/bin" ] ; then
	mkdir ${HOME}/bin
fi
export PATH="${HOME}/bin:$PATH"
if [ "$(uname)" = "Darwin" ]; then
#	export PATH="/sbin:$PATH"
	export PATH=${PATH}:~/Library/Python/2.7/bin
#	export PATH=${PATH}:/Applications/lb5pa1
	export PATH=${PATH}:/Applications/lb5pa2
#else
fi
# set PATH so it includes user's private bin if it exists
if [[ ! $PATH =~ .*:/usr/local/mailman/bin:.* ]]; then
	export PATH="${PATH}:/usr/local/mailman/bin"
fi
#export PATH="/usr/local/opt/ssh-copy-id/bin:$PATH"
#export PATH="/usr/local/opt/findutils/libexec/gnubin:${PATH}"
export PATH="/bin:${PATH}"
export PATH="/Applications/basex/bin:${PATH}"
# Set app PATHs
export MANPATH="/usr/local/share/man/man1:/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export ZPLUG_HOME=${HOME}/.zplug
export HELPDIR='/usr/local/shalre/zsh/help'
export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"
export PGPPATH=~/.pgp
export DOTDROPDIR="${HOME}/dotfiles.git"
export DOTFILESDIR="${HOME}/dotfiles.git/dotdrop"
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
path_remove /usr/local/bin # added to front of PATH
export PATH="/usr/local/bin:${PATH}"
